name: publish
on: { push: { branches: [main] } }
permissions: { id-token: write, contents: read }
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - run: npm i -fg corepack && corepack enable
      - uses: actions/setup-node@v5
        with:
          node-version: lts/*
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"
      - run: pnpm install
      - run: pnpm changelogen --bump --canary nightly
      - run: npm i -g npm@latest && npm publish --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
